apiVersion: apps/v1
kind: Deployment
metadata:
  name: scandalorian-ingest
  namespace: scandalorian
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: scandalorian-ingest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scandalorian-ingest
    spec:
      containers:
      - image: charlesdburton/scandalorian-ingest:latest
        imagePullPolicy: Always
        env:
        - name: INGEST_BUSHOST
          value: "nats.default.svc"
        - name: INGEST_PORT
          value: "4222"
        name: scandalorian-ingest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 9090
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: scandalorian-ingest
  namespace: scandalorian
  labels:
    app: scandalorian-ingest
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
  type: LoadBalancer
  selector:
    app: scandalorian-ingest
